name: Docker nightly build

env:
  DOCKER_TAG: ${{ github.sha }}

on:
  push:
  workflow_dispatch:

permissions: {}

jobs:
  build_image:
    if: ${{ github.event_name != 'push' || contains(github.event.head_commit.message, 'docker_build') }}
    name: Build Docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6

      - name: Setup QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_GITHUB_TOKEN }}

      - name: Build and push Linux
        uses: docker/build-push-action@v6
        with:
          file: dockerfiles/Dockerfile
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/yetsing/canvas_pyr/ubuntu-builder:${{ env.DOCKER_TAG }}
            ghcr.io/yetsing/canvas_pyr/ubuntu-builder:latest

      - name: Install latest libc++-dev for cross build
        uses: addnab/docker-run-action@v3
        with:
          image: ubuntu:jammy
          options: '--platform linux/arm64 --user 0:0 -v ${{ github.workspace }}/lib/llvm-19:/usr/lib/llvm-19'
          run: >-
            apt-get update &&
            apt-get install -y wget gnupg2 &&
            wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - &&
            echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main" >> /etc/apt/sources.list &&
            echo "deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main" >> /etc/apt/sources.list &&
            apt-get update &&
            apt-get install libc++-19-dev libc++abi-19-dev -y --fix-missing --no-install-recommends &&
            rm /usr/lib/llvm-19/lib/libc++abi.so &&
            rm /usr/lib/llvm-19/lib/libunwind.so &&
            rm /usr/lib/llvm-19/lib/libc++.so

      - name: Build and push Linux aarch64
        uses: docker/build-push-action@v6
        with:
          file: dockerfiles/aarch64.Dockerfile
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/yetsing/canvas_pyr/ubuntu-builder:aarch64-${{ env.DOCKER_TAG }}
            ghcr.io/yetsing/canvas_pyr/ubuntu-builder:aarch64-latest
